### PR TITLE
R8DIUM Bot Updates

### PR DESCRIPTION
**Pull request by Killerp51**
Fixed - audioop-lts file missing (added into requirements.txt for install)
Added - Discord bot activity status (incorporated into config.cfg -set to Run8 by default)
Added - Discord role assignment upon member joining server (optional - disabled by default)

### CODE REVIEW

**Comment by sjstein** [comment]
Please explain what functionality you are adding with this branch. 
Thank you!

**Comment by Killerp51** [comment]
The functionality added is focused on the Discord bot and user management in the server, making the bot more capable and relying less on extra bots:

- Discord Bot activity status - Ability to set a bot activity status such as "Playing Run8" or "Playing Run8 on the Depot +" etc. Instructions and ability to disable the feature included in config.cfg so users don't need to edit python code. Used existing configparser to grab BOT_STATUS.
- Discord role assignment - Many discord servers use an initial role to ping new members such as "Foamer" or "Recruit" for example. This feature allows a discord owner to set a role that is assigned when a user joins a Discord. Instructions included in config.cfg but disabled by default. Used the existing configparser to grab DISCORD_ROLE

Lastly, the Gravitated release was throwing an error for missing audioop-lts with Python 3.13. Added audioop-lts to the requirements.txt file so that when users go through the install process it works with no additional changes. 

The readme commits were for a separate fork before I realized I could do a pull request. Removed the changes before the pull. I'm new to using github with others so that was a learning moment

I hope this helps! Happy to answer any further questions or type up additional guidance if required.

**Comment by Killerp51** [comment]
Example of R8DIUM Bot with activity status
image
Example of R8DIUM Bot without status
image

**Comment by sjstein** [comment]
Thanks for the explanation @Killerp51!

The audioop-lts is annoying in that r8dium doesn't use any audio, but I suspect the discord library has audioop as a dependency (the now deprecated one). 

I cringe at putting a dependency in the requirements for a library that r8dium doesn't explicitly use; but don't despair - I'll look into other options asap.

The other changes I believe I understand and are welcome additions.

Stay tuned!

**Comment by sjstein** [comment]
@Killerp51 - the issue with audioop seems to stem from the discord/player.py (see https://github.com/Rapptz/discord.py/blob/master/discord/player.py) - and until the author sees fit to update that import (of audioop), the error will occur for python versions > 3.12

To make it a bit clearer, would you consider changing your requirements.txt line 5 to:
`audioop-lts >=0.2.1; python_version>='3.13'` ?

**Comment by sjstein** [comment]
@Killerp51, upon closer review of your feature addition of the _auto role assignment_, I'm hesitant to add that for three reasons:
1. This functionality is out of scope of the original intent of r8dium
2. This functionality would require more permissions be opened up by the server owner - something I would like to avoid
3. This functionality is already available on a few other (popular) bots such as MEE6, YAGPDB, Autoroles, and others

Would you consider removing this feature from your update?

If it important to your specific use case, you can always fork this repo and develop in parallel

**Comment by Killerp51** [comment]
@sjstein - thanks for looking into the audioop-lts issue! It is frustrating but `audioop-lts >=0.2.1; python_version>='3.13' # only required until discord updates their api dependency on audioop` should prevent errors in the meantime.

Completely understand your point on the scope of the bot and roles. All discord role functionality has been removed and the pull request updated

**Review by sjstein — APPROVED** [review]
Per pull request convo

**Pull request merged**
